<div align="right" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/Logo blue_dark.png"  style="width:25px" align="right";/>
</div>

# Grouping with a CASE statement
© ExploreAI Academy

In this notebook, we learn how to use the `CASE` statement to categorise and group data.

> ⚠️ This notebook will not run on Google Colab because it cannot connect to a local database. Please make sure that this notebook is running on the same local machine as your MySQL Workbench installation and MySQL `united_nations` database.

## Learning objectives

By the end of this train, you should:
- Know how to categorise data using `CASE` statements.
- Know how to combine `CASE` statements with aggregate functions for enhanced data summarisation.
- Understand how to use the `GROUP BY` clause with the `CASE` statement.

## Connecting to our MySQL database

Using our `Access_to_Basic_Services` table created in MySQL Workbench, we want to answer some questions on the range of our dataset. We can apply the same queries in MySQL Workbench and in this notebook if we connect to our MySQL server. Since we have a MySQL database, we can connect to it using mysql and pymysql.

In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql are installed correctly. 

%reload_ext sql

In [2]:
# Establish a connection to the local database using the '%sql' magic command.
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://root:password@localhost:3306/united_nations

## Exercise

The following table specifies which countries belong to each Regional Economic Community (REC):

| Regional Economic Community | Countries |
|----------------------------|------------|
| SADC                       | Angola, Botswana, Comoros, Democratic Republic of Congo, Eswatini, Lesotho, Madagascar, Malawi, Mauritius, Mozambique, Namibia, Seychelles, South Africa, United Republic Tanzania, Zambia, Zimbabwe |
| UMA                        | Algeria, Libya, Mauritania, Morocco, Tunisia |
| ECOWAS                     | Benin, Burkina Faso, Cabo Verde, Cote d’Ivoire, Gambia, Ghana, Guinea, Guinea-Bissau, Liberia, Mali, Niger, Nigeria, Senegal, Sierra Leone, Togo |
| Not Classified             | Other countries not listed above |

We will use this table when constructing our queries.

### 1. Identify regions in Africa

Construct a query that selects only the regions falling within Africa. Use the `LIKE` operator to identify records where the `Region` contains `Africa`.

In [3]:
%%sql
SELECT
    *
FROM
    united_nations.Access_to_Basic_Services
WHERE
    region LIKE '%Africa%'
LIMIT 5;

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2015, Decimal('92.00'), Decimal('85.00'), Decimal('39.543154'), Decimal('165.98'), Decimal('2381741.00'), Decimal('11.21')),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2016, Decimal('93.00'), Decimal('85.33'), Decimal('40.339329'), Decimal('160.03'), Decimal('2381741.00'), Decimal('10.20')),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2017, Decimal('93.00'), Decimal('84.67'), Decimal('41.136546'), Decimal('170.10'), Decimal('2381741.00'), Decimal('12.00')),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2018, Decimal('93.00'), Decimal('84.67'), Decimal('41.927007'), Decimal('174.91'), Decimal('2381741.00'), None),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2019, Decimal('93.33'), Decimal('84.67'), Decimal('42.705368'), Decimal('171.77'), Decimal('2381741.00'), None)]

### 2. Classify SADC countries

Use a `CASE` statement to classify whether an African country belongs to SADC, or does not belong to SADC. In other words, if the `country_name` is one of the names we specified as an SADC country (in the table above), it should be classified as SADC. Otherwise, it must be classified as  `Not Classified`.

The query should return three columns:
- An alias, `Regional_economic_community`, that contains the results of the `CASE` statement
- `Country_name`
- `Pct_managed_drinking_water_services`

In [4]:
%%sql

SELECT
    Country_name,
    Pct_managed_drinking_water_services,
    CASE
        WHEN Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 'Lesotho', 'Madagascar', 
        'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
        THEN 'SADC'
    ELSE 'Not Classified'
    END AS Regional_economic_community
FROM
    united_nations.Access_to_Basic_Services
WHERE
    region LIKE '%Africa%';

 * mysql+pymysql://root:***@localhost:3306/united_nations
441 rows affected.

[('Algeria', Decimal('92.00'), 'Not Classified'),
 ('Algeria', Decimal('93.00'), 'Not Classified'),
 ('Algeria', Decimal('93.00'), 'Not Classified'),
 ('Algeria', Decimal('93.00'), 'Not Classified'),
 ('Algeria', Decimal('93.33'), 'Not Classified'),
 ('Algeria', Decimal('93.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Libya', Decimal('97.00'), 'Not Classified'),
 ('Libya', Decimal('98.00'), 'Not Classified'),
 ('Libya', Decimal('99.00'), 'Not Classified'),
 ('Libya', Decimal('100.00'), 'Not Classified'),
 ('Libya', Decimal('100.00'), 'Not Classified'),
 ('Libya', Decimal('100.00'), 'Not Classified'),
 ('Morocco', Decimal('81.33'), 'Not Classified'),
 ('Morocco', Decimal('83.00'), 'Not Classified'),
 ('Morocco', Decimal('84.00'), 'Not Classified'),
 ('Morocco', Decimal('85.67'), 'Not Classified'),
 ('Morocco', Decimal('87.33'), 'Not Classified'),
 ('Morocco', Decimal('88.33'), 'Not Classified'),
 ('Sudan', Decimal('61.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Tunisia', Decimal('93.33'), 'Not Classified'),
 ('Tunisia', Decimal('93.67'), 'Not Classified'),
 ('Tunisia', Decimal('94.67'), 'Not Classified'),
 ('Tunisia', Decimal('95.67'), 'Not Classified'),
 ('Tunisia', Decimal('96.00'), 'Not Classified'),
 ('Tunisia', Decimal('97.00'), 'Not Classified'),
 ('Armenia', Decimal('99.67'), 'Not Classified'),
 ('Armenia', Decimal('99.67'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Azerbaijan', Decimal('91.67'), 'Not Classified'),
 ('Azerbaijan', Decimal('92.33'), 'Not Classified'),
 ('Azerbaijan', Decimal('93.67'), 'Not Classified'),
 ('Azerbaijan', Decimal('94.33'), 'Not Classified'),
 ('Azerbaijan', Decimal('95.00'), 'Not Classified'),
 ('Azerbaijan', Decimal('95.67'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Georgia', Decimal('95.33'), 'Not Classified'),
 ('Georgia', Decimal('96.00'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Iraq', Decimal('92.33'), 'Not Classified'),
 ('Iraq', Decimal('93.67'), 'Not Classified'),
 ('Iraq', Decimal('94.67'), 'Not Classified'),
 ('Iraq', Decimal('95.67'), 'Not Classified'),
 ('Iraq', Decimal('97.00'), 'Not Classified'),
 ('Iraq', Decimal('97.67'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Lebanon', Decimal('91.00'), 'Not Classified'),
 ('Lebanon', Decimal('92.00'), 'Not Classified'),
 ('Lebanon', Decimal('92.00'), 'Not Classified'),
 ('Lebanon', Decimal('92.00'), 'Not Classified'),
 ('Lebanon', Decimal('93.00'), 'Not Classified'),
 ('Lebanon', Decimal('93.00'), 'Not Classified'),
 ('Oman', Decimal('86.00'), 'Not Classified'),
 ('Oman', Decimal('86.67'), 'Not Classified'),
 ('Oman', Decimal('86.67'), 'Not Classified'),
 ('Oman', Decimal('87.00'), 'Not Classified'),
 ('Oman', Decimal('87.67'), 'Not Classified'),
 ('Oman', Decimal('87.67'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('State of Palestine', Decimal('96.00'), 'Not Classified'),
 ('State of Palestine', Decimal('96.67'), 'Not Classified'),
 ('State of Palestine', Decimal('97.00'), 'Not Classified'),
 ('State of Palestine', Decimal('97.00'), 'Not Classified'),
 ('State of Palestine', Decimal('97.67'), 'Not Classified'),
 ('State of Palestine', Decimal('98.33'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.33'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Türkiye', Decimal('95.67'), 'Not Classified'),
 ('Türkiye', Decimal('96.00'), 'Not Classified'),
 ('Türkiye', Decimal('96.33'), 'Not Classified'),
 ('Türkiye', Decimal('96.33'), 'Not Classified'),
 ('Türkiye', Decimal('96.67'), 'Not Classified'),
 ('Türkiye', Decimal('96.67'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('Yemen', Decimal('59.00'), 'Not Classified'),
 ('Yemen', Decimal('59.67'), 'Not Classified'),
 ('Yemen', Decimal('60.33'), 'Not Classified'),
 ('Yemen', Decimal('61.33'), 'Not Classified'),
 ('Yemen', Decimal('62.33'), 'Not Classified'),
 ('Yemen', Decimal('63.00'), 'Not Classified'),
 ('Burundi', Decimal('68.33'), 'Not Classified'),
 ('Burundi', Decimal('68.33'), 'Not Classified'),
 ('Burundi', Decimal('69.33'), 'Not Classified'),
 ('Burundi', Decimal('69.33'), 'Not Classified'),
 ('Burundi', Decimal('70.33'), 'Not Classified'),
 ('Burundi', Decimal('70.33'), 'Not Classified'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Djibouti', Decimal('69.67'), 'Not Classified'),
 ('Djibouti', Decimal('69.33'), 'Not Classified'),
 ('Djibouti', Decimal('69.33'), 'Not Classified'),
 ('Djibouti', Decimal('69.33'), 'Not Classified'),
 ('Djibouti', Decimal('69.00'), 'Not Classified'),
 ('Djibouti', Decimal('69.00'), 'Not Classified'),
 ('Eritrea', Decimal('56.33'), 'Not Classified'),
 ('Eritrea', Decimal('56.67'), 'Not Classified'),
 ('Ethiopia', Decimal('52.00'), 'Not Classified'),
 ('Ethiopia', Decimal('53.33'), 'Not Classified'),
 ('Ethiopia', Decimal('54.67'), 'Not Classified'),
 ('Ethiopia', Decimal('55.67'), 'Not Classified'),
 ('Ethiopia', Decimal('57.00'), 'Not Classified'),
 ('Ethiopia', Decimal('58.00'), 'Not Classified'),
 ('Kenya', Decimal('64.33'), 'Not Classified'),
 ('Kenya', Decimal('65.00'), 'Not Classified'),
 ('Kenya', Decimal('65.67'), 'Not Classified'),
 ('Kenya', Decimal('65.67'), 'Not Classified'),
 ('Kenya', Decimal('66.33'), 'Not Classified'),
 ('Kenya', Decimal('67.00'), 'Not Classified'),
 ('Madagascar', Decimal('53.33'), 'SADC'),
 ('Madagascar', Decimal('54.00'), 'SADC'),
 ('Madagascar', Decimal('54.67'), 'SADC'),
 ('Madagascar', Decimal('55.33'), 'SADC'),
 ('Madagascar', Decimal('56.00'), 'SADC'),
 ('Madagascar', Decimal('56.33'), 'SADC'),
 ('Malawi', Decimal('71.33'), 'SADC'),
 ('Malawi', Decimal('72.00'), 'SADC'),
 ('Malawi', Decimal('72.67'), 'SADC'),
 ('Malawi', Decimal('73.33'), 'SADC'),
 ('Malawi', Decimal('73.67'), 'SADC'),
 ('Malawi', Decimal('74.33'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mayotte', Decimal('97.00'), 'Not Classified'),
 ('Mayotte', Decimal('97.00'), 'Not Classified'),
 ('Mayotte', Decimal('97.00'), 'Not Classified'),
 ('Mayotte', Decimal('96.00'), 'Not Classified'),
 ('Mayotte', Decimal('96.00'), 'Not Classified'),
 ('Mayotte', Decimal('96.00'), 'Not Classified'),
 ('Mozambique', Decimal('55.67'), 'SADC'),
 ('Mozambique', Decimal('58.00'), 'SADC'),
 ('Mozambique', Decimal('60.00'), 'SADC'),
 ('Mozambique', Decimal('62.33'), 'SADC'),
 ('Mozambique', Decimal('64.33'), 'SADC'),
 ('Mozambique', Decimal('66.67'), 'SADC'),
 ('Rwanda', Decimal('63.00'), 'Not Classified'),
 ('Rwanda', Decimal('64.00'), 'Not Classified'),
 ('Rwanda', Decimal('65.00'), 'Not Classified'),
 ('Rwanda', Decimal('65.67'), 'Not Classified'),
 ('Rwanda', Decimal('66.33'), 'Not Classified'),
 ('Rwanda', Decimal('66.33'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('97.00'), 'SADC'),
 ('Somalia', Decimal('50.67'), 'Not Classified'),
 ('Somalia', Decimal('52.00'), 'Not Classified'),
 ('Somalia', Decimal('53.33'), 'Not Classified'),
 ('Somalia', Decimal('54.67'), 'Not Classified'),
 ('Somalia', Decimal('56.33'), 'Not Classified'),
 ('Somalia', Decimal('57.33'), 'Not Classified'),
 ('South Sudan', Decimal('46.33'), 'Not Classified'),
 ('South Sudan', Decimal('46.67'), 'Not Classified'),
 ('South Sudan', Decimal('47.00'), 'Not Classified'),
 ('South Sudan', Decimal('47.67'), 'Not Classified'),
 ('South Sudan', Decimal('48.33'), 'Not Classified'),
 ('South Sudan', Decimal('48.33'), 'Not Classified'),
 ('Uganda', Decimal('55.00'), 'Not Classified'),
 ('Uganda', Decimal('55.67'), 'Not Classified'),
 ('Uganda', Decimal('57.00'), 'Not Classified'),
 ('Uganda', Decimal('58.67'), 'Not Classified'),
 ('Uganda', Decimal('59.33'), 'Not Classified'),
 ('Uganda', Decimal('61.00'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('58.33'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('60.00'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('61.67'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('63.33'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('64.67'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('65.00'), 'Not Classified'),
 ('Zambia', Decimal('63.67'), 'SADC'),
 ('Zambia', Decimal('64.33'), 'SADC'),
 ('Zambia', Decimal('64.67'), 'SADC'),
 ('Zambia', Decimal('65.33'), 'SADC'),
 ('Zambia', Decimal('66.33'), 'SADC'),
 ('Zambia', Decimal('66.67'), 'SADC'),
 ('Zimbabwe', Decimal('70.00'), 'SADC'),
 ('Zimbabwe', Decimal('69.33'), 'SADC'),
 ('Zimbabwe', Decimal('69.00'), 'SADC'),
 ('Zimbabwe', Decimal('68.67'), 'SADC'),
 ('Zimbabwe', Decimal('68.33'), 'SADC'),
 ('Zimbabwe', Decimal('68.00'), 'SADC'),
 ('Angola', Decimal('50.33'), 'SADC'),
 ('Angola', Decimal('51.00'), 'SADC'),
 ('Angola', Decimal('51.33'), 'SADC'),
 ('Angola', Decimal('52.33'), 'SADC'),
 ('Angola', Decimal('52.33'), 'SADC'),
 ('Angola', Decimal('52.33'), 'SADC'),
 ('Cameroon', Decimal('62.67'), 'Not Classified'),
 ('Cameroon', Decimal('62.67'), 'Not Classified'),
 ('Cameroon', Decimal('63.33'), 'Not Classified'),
 ('Cameroon', Decimal('63.33'), 'Not Classified'),
 ('Cameroon', Decimal('63.33'), 'Not Classified'),
 ('Cameroon', Decimal('64.00'), 'Not Classified'),
 ('Central African Republic', Decimal('44.00'), 'Not Classified'),
 ('Central African Republic', Decimal('42.67'), 'Not Classified'),
 ('Central African Republic', Decimal('41.33'), 'Not Classified'),
 ('Central African Republic', Decimal('40.67'), 'Not Classified'),
 ('Central African Republic', Decimal('39.33'), 'Not Classified'),
 ('Central African Republic', Decimal('38.33'), 'Not Classified'),
 ('Chad', Decimal('51.67'), 'Not Classified'),
 ('Chad', Decimal('52.00'), 'Not Classified'),
 ('Chad', Decimal('52.00'), 'Not Classified'),
 ('Chad', Decimal('52.00'), 'Not Classified'),
 ('Chad', Decimal('52.33'), 'Not Classified'),
 ('Chad', Decimal('52.67'), 'Not Classified'),
 ('Congo', Decimal('66.33'), 'Not Classified'),
 ('Congo', Decimal('67.67'), 'Not Classified'),
 ('Congo', Decimal('68.67'), 'Not Classified'),
 ('Congo', Decimal('68.67'), 'Not Classified'),
 ('Congo', Decimal('69.00'), 'Not Classified'),
 ('Congo', Decimal('69.00'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('45.33'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('45.67'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('46.00'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('46.67'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('47.00'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('47.67'), 'Not Classified'),
 ('Equatorial Guinea', Decimal('57.67'), 'Not Classified'),
 ('Equatorial Guinea', Decimal('57.67'), 'Not Classified'),
 ('Equatorial Guinea', Decimal('58.00'), 'Not Classified'),
 ('Gabon', Decimal('72.00'), 'Not Classified'),
 ('Gabon', Decimal('72.33'), 'Not Classified'),
 ('Gabon', Decimal('73.00'), 'Not Classified'),
 ('Gabon', Decimal('73.00'), 'Not Classified'),
 ('Gabon', Decimal('73.33'), 'Not Classified'),
 ('Gabon', Decimal('73.33'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('76.00'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('76.67'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.00'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.00'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.33'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.33'), 'Not Classified'),
 ('Botswana', Decimal('85.67'), 'SADC'),
 ('Botswana', Decimal('86.67'), 'SADC'),
 ('Botswana', Decimal('87.67'), 'SADC'),
 ('Botswana', Decimal('88.33'), 'SADC'),
 ('Botswana', Decimal('89.67'), 'SADC'),
 ('Botswana', Decimal('89.67'), 'SADC'),
 ('Eswatini', Decimal('73.33'), 'SADC'),
 ('Eswatini', Decimal('74.00'), 'SADC'),
 ('Eswatini', Decimal('75.00'), 'SADC'),
 ('Eswatini', Decimal('75.67'), 'SADC'),
 ('Eswatini', Decimal('76.67'), 'SADC'),
 ('Eswatini', Decimal('76.67'), 'SADC'),
 ('Lesotho', Decimal('74.67'), 'SADC'),
 ('Lesotho', Decimal('75.00'), 'SADC'),
 ('Lesotho', Decimal('75.33'), 'SADC'),
 ('Lesotho', Decimal('76.00'), 'SADC'),
 ('Lesotho', Decimal('76.00'), 'SADC'),
 ('Lesotho', Decimal('76.33'), 'SADC'),
 ('Namibia', Decimal('83.33'), 'SADC'),
 ('Namibia', Decimal('83.00'), 'SADC'),
 ('Namibia', Decimal('83.33'), 'SADC'),
 ('Namibia', Decimal('83.67'), 'SADC'),
 ('Namibia', Decimal('83.67'), 'SADC'),
 ('Namibia', Decimal('83.67'), 'SADC'),
 ('South Africa', Decimal('90.00'), 'SADC'),
 ('South Africa', Decimal('90.33'), 'SADC'),
 ('South Africa', Decimal('91.00'), 'SADC'),
 ('South Africa', Decimal('91.33'), 'SADC'),
 ('South Africa', Decimal('91.67'), 'SADC'),
 ('South Africa', Decimal('92.00'), 'SADC'),
 ('Benin', Decimal('65.33'), 'Not Classified'),
 ('Benin', Decimal('65.33'), 'Not Classified'),
 ('Benin', Decimal('65.33'), 'Not Classified'),
 ('Benin', Decimal('65.67'), 'Not Classified'),
 ('Benin', Decimal('65.33'), 'Not Classified'),
 ('Benin', Decimal('65.33'), 'Not Classified'),
 ('Burkina Faso', Decimal('56.33'), 'Not Classified'),
 ('Burkina Faso', Decimal('56.00'), 'Not Classified'),
 ('Burkina Faso', Decimal('55.00'), 'Not Classified'),
 ('Burkina Faso', Decimal('54.33'), 'Not Classified'),
 ('Burkina Faso', Decimal('54.00'), 'Not Classified'),
 ('Burkina Faso', Decimal('53.33'), 'Not Classified'),
 ('Cabo Verde', Decimal('83.33'), 'Not Classified'),
 ('Cabo Verde', Decimal('84.33'), 'Not Classified'),
 ('Cabo Verde', Decimal('85.33'), 'Not Classified'),
 ('Cabo Verde', Decimal('86.00'), 'Not Classified'),
 ('Cabo Verde', Decimal('86.67'), 'Not Classified'),
 ('Cabo Verde', Decimal('87.33'), 'Not Classified'),
 ("Côte d'Ivoire", Decimal('71.33'), 'Not Classified'),
 ("Côte d'Ivoire", Decimal('71.00'), 'Not Classified'),
 ("Côte d'Ivoire", Decimal('71.00'), 'Not Classified'),
 ("Côte d'Ivoire", Decimal('71.00'), 'Not Classified'),
 ("Côte d'Ivoire", Decimal('70.67'), 'Not Classified'),
 ("Côte d'Ivoire", Decimal('70.67'), 'Not Classified'),
 ('Gambia', Decimal('78.00'), 'Not Classified'),
 ('Gambia', Decimal('78.33'), 'Not Classified'),
 ('Gambia', Decimal('78.67'), 'Not Classified'),
 ('Gambia', Decimal('78.67'), 'Not Classified'),
 ('Gambia', Decimal('79.33'), 'Not Classified'),
 ('Gambia', Decimal('79.33'), 'Not Classified'),
 ('Ghana', Decimal('79.33'), 'Not Classified'),
 ('Ghana', Decimal('80.33'), 'Not Classified'),
 ('Ghana', Decimal('81.33'), 'Not Classified'),
 ('Ghana', Decimal('82.67'), 'Not Classified'),
 ('Ghana', Decimal('83.67'), 'Not Classified'),
 ('Ghana', Decimal('84.67'), 'Not Classified'),
 ('Guinea', Decimal('67.00'), 'Not Classified'),
 ('Guinea', Decimal('67.00'), 'Not Classified'),
 ('Guinea', Decimal('67.33'), 'Not Classified'),
 ('Guinea', Decimal('67.00'), 'Not Classified'),
 ('Guinea', Decimal('67.00'), 'Not Classified'),
 ('Guinea', Decimal('67.33'), 'Not Classified'),
 ('Guinea-Bissau', Decimal('60.00'), 'Not Classified'),
 ('Guinea-Bissau', Decimal('60.33'), 'Not Classified'),
 ('Guinea-Bissau', Decimal('60.00'), 'Not Classified'),
 ('Guinea-Bissau', Decimal('60.00'), 'Not Classified'),
 ('Guinea-Bissau', Decimal('60.00'), 'Not Classified'),
 ('Guinea-Bissau', Decimal('60.00'), 'Not Classified'),
 ('Liberia', Decimal('72.67'), 'Not Classified'),
 ('Liberia', Decimal('73.00'), 'Not Classified'),
 ('Liberia', Decimal('74.00'), 'Not Classified'),
 ('Liberia', Decimal('74.00'), 'Not Classified'),
 ('Liberia', Decimal('75.00'), 'Not Classified'),
 ('Liberia', Decimal('75.00'), 'Not Classified'),
 ('Mali', Decimal('76.00'), 'Not Classified'),
 ('Mali', Decimal('77.67'), 'Not Classified'),
 ('Mali', Decimal('79.33'), 'Not Classified'),
 ('Mali', Decimal('80.67'), 'Not Classified'),
 ('Mali', Decimal('82.00'), 'Not Classified'),
 ('Mali', Decimal('83.67'), 'Not Classified'),

### 3. Classify UMA and ECOWAS countries

Add to the `CASE` statement to include classifications for the UMA and ECOWAS RECS. Classify the countries based on the table above.

In [5]:
%%sql

SELECT
    Country_name,
    Pct_managed_drinking_water_services,
    CASE
        WHEN 
            Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 'Lesotho', 'Madagascar', 
            'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
        THEN
            'SADC'
        WHEN 
            Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
        THEN
            'UMA'
        WHEN
            Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', "Cote d'Ivoire", 'Gambia', 'Ghana', 
                            'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
        THEN 
            'ECOWAS'
        ELSE 
            'Not Classified'
    END AS Regional_economic_community 
FROM
    united_nations.Access_to_Basic_Services
WHERE
    region LIKE '%Africa%';

 * mysql+pymysql://root:***@localhost:3306/united_nations
441 rows affected.

[('Algeria', Decimal('92.00'), 'UMA'),
 ('Algeria', Decimal('93.00'), 'UMA'),
 ('Algeria', Decimal('93.00'), 'UMA'),
 ('Algeria', Decimal('93.00'), 'UMA'),
 ('Algeria', Decimal('93.33'), 'UMA'),
 ('Algeria', Decimal('93.33'), 'UMA'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Egypt', Decimal('99.33'), 'Not Classified'),
 ('Libya', Decimal('97.00'), 'UMA'),
 ('Libya', Decimal('98.00'), 'UMA'),
 ('Libya', Decimal('99.00'), 'UMA'),
 ('Libya', Decimal('100.00'), 'UMA'),
 ('Libya', Decimal('100.00'), 'UMA'),
 ('Libya', Decimal('100.00'), 'UMA'),
 ('Morocco', Decimal('81.33'), 'UMA'),
 ('Morocco', Decimal('83.00'), 'UMA'),
 ('Morocco', Decimal('84.00'), 'UMA'),
 ('Morocco', Decimal('85.67'), 'UMA'),
 ('Morocco', Decimal('87.33'), 'UMA'),
 ('Morocco', Decimal('88.33'), 'UMA'),
 ('Sudan', Decimal('61.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Sudan', Decimal('62.33'), 'Not Classified'),
 ('Tunisia', Decimal('93.33'), 'UMA'),
 ('Tunisia', Decimal('93.67'), 'UMA'),
 ('Tunisia', Decimal('94.67'), 'UMA'),
 ('Tunisia', Decimal('95.67'), 'UMA'),
 ('Tunisia', Decimal('96.00'), 'UMA'),
 ('Tunisia', Decimal('97.00'), 'UMA'),
 ('Armenia', Decimal('99.67'), 'Not Classified'),
 ('Armenia', Decimal('99.67'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Armenia', Decimal('100.00'), 'Not Classified'),
 ('Azerbaijan', Decimal('91.67'), 'Not Classified'),
 ('Azerbaijan', Decimal('92.33'), 'Not Classified'),
 ('Azerbaijan', Decimal('93.67'), 'Not Classified'),
 ('Azerbaijan', Decimal('94.33'), 'Not Classified'),
 ('Azerbaijan', Decimal('95.00'), 'Not Classified'),
 ('Azerbaijan', Decimal('95.67'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Bahrain', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Cyprus', Decimal('100.00'), 'Not Classified'),
 ('Georgia', Decimal('95.33'), 'Not Classified'),
 ('Georgia', Decimal('96.00'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Georgia', Decimal('96.67'), 'Not Classified'),
 ('Iraq', Decimal('92.33'), 'Not Classified'),
 ('Iraq', Decimal('93.67'), 'Not Classified'),
 ('Iraq', Decimal('94.67'), 'Not Classified'),
 ('Iraq', Decimal('95.67'), 'Not Classified'),
 ('Iraq', Decimal('97.00'), 'Not Classified'),
 ('Iraq', Decimal('97.67'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Israel', Decimal('100.00'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Jordan', Decimal('98.33'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Kuwait', Decimal('100.00'), 'Not Classified'),
 ('Lebanon', Decimal('91.00'), 'Not Classified'),
 ('Lebanon', Decimal('92.00'), 'Not Classified'),
 ('Lebanon', Decimal('92.00'), 'Not Classified'),
 ('Lebanon', Decimal('92.00'), 'Not Classified'),
 ('Lebanon', Decimal('93.00'), 'Not Classified'),
 ('Lebanon', Decimal('93.00'), 'Not Classified'),
 ('Oman', Decimal('86.00'), 'Not Classified'),
 ('Oman', Decimal('86.67'), 'Not Classified'),
 ('Oman', Decimal('86.67'), 'Not Classified'),
 ('Oman', Decimal('87.00'), 'Not Classified'),
 ('Oman', Decimal('87.67'), 'Not Classified'),
 ('Oman', Decimal('87.67'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Qatar', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('Saudi Arabia', Decimal('100.00'), 'Not Classified'),
 ('State of Palestine', Decimal('96.00'), 'Not Classified'),
 ('State of Palestine', Decimal('96.67'), 'Not Classified'),
 ('State of Palestine', Decimal('97.00'), 'Not Classified'),
 ('State of Palestine', Decimal('97.00'), 'Not Classified'),
 ('State of Palestine', Decimal('97.67'), 'Not Classified'),
 ('State of Palestine', Decimal('98.33'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.33'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Syrian Arab Republic', Decimal('93.67'), 'Not Classified'),
 ('Türkiye', Decimal('95.67'), 'Not Classified'),
 ('Türkiye', Decimal('96.00'), 'Not Classified'),
 ('Türkiye', Decimal('96.33'), 'Not Classified'),
 ('Türkiye', Decimal('96.33'), 'Not Classified'),
 ('Türkiye', Decimal('96.67'), 'Not Classified'),
 ('Türkiye', Decimal('96.67'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('United Arab Emirates', Decimal('100.00'), 'Not Classified'),
 ('Yemen', Decimal('59.00'), 'Not Classified'),
 ('Yemen', Decimal('59.67'), 'Not Classified'),
 ('Yemen', Decimal('60.33'), 'Not Classified'),
 ('Yemen', Decimal('61.33'), 'Not Classified'),
 ('Yemen', Decimal('62.33'), 'Not Classified'),
 ('Yemen', Decimal('63.00'), 'Not Classified'),
 ('Burundi', Decimal('68.33'), 'Not Classified'),
 ('Burundi', Decimal('68.33'), 'Not Classified'),
 ('Burundi', Decimal('69.33'), 'Not Classified'),
 ('Burundi', Decimal('69.33'), 'Not Classified'),
 ('Burundi', Decimal('70.33'), 'Not Classified'),
 ('Burundi', Decimal('70.33'), 'Not Classified'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Comoros', Decimal('81.67'), 'SADC'),
 ('Djibouti', Decimal('69.67'), 'Not Classified'),
 ('Djibouti', Decimal('69.33'), 'Not Classified'),
 ('Djibouti', Decimal('69.33'), 'Not Classified'),
 ('Djibouti', Decimal('69.33'), 'Not Classified'),
 ('Djibouti', Decimal('69.00'), 'Not Classified'),
 ('Djibouti', Decimal('69.00'), 'Not Classified'),
 ('Eritrea', Decimal('56.33'), 'Not Classified'),
 ('Eritrea', Decimal('56.67'), 'Not Classified'),
 ('Ethiopia', Decimal('52.00'), 'Not Classified'),
 ('Ethiopia', Decimal('53.33'), 'Not Classified'),
 ('Ethiopia', Decimal('54.67'), 'Not Classified'),
 ('Ethiopia', Decimal('55.67'), 'Not Classified'),
 ('Ethiopia', Decimal('57.00'), 'Not Classified'),
 ('Ethiopia', Decimal('58.00'), 'Not Classified'),
 ('Kenya', Decimal('64.33'), 'Not Classified'),
 ('Kenya', Decimal('65.00'), 'Not Classified'),
 ('Kenya', Decimal('65.67'), 'Not Classified'),
 ('Kenya', Decimal('65.67'), 'Not Classified'),
 ('Kenya', Decimal('66.33'), 'Not Classified'),
 ('Kenya', Decimal('67.00'), 'Not Classified'),
 ('Madagascar', Decimal('53.33'), 'SADC'),
 ('Madagascar', Decimal('54.00'), 'SADC'),
 ('Madagascar', Decimal('54.67'), 'SADC'),
 ('Madagascar', Decimal('55.33'), 'SADC'),
 ('Madagascar', Decimal('56.00'), 'SADC'),
 ('Madagascar', Decimal('56.33'), 'SADC'),
 ('Malawi', Decimal('71.33'), 'SADC'),
 ('Malawi', Decimal('72.00'), 'SADC'),
 ('Malawi', Decimal('72.67'), 'SADC'),
 ('Malawi', Decimal('73.33'), 'SADC'),
 ('Malawi', Decimal('73.67'), 'SADC'),
 ('Malawi', Decimal('74.33'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mauritius', Decimal('100.00'), 'SADC'),
 ('Mayotte', Decimal('97.00'), 'Not Classified'),
 ('Mayotte', Decimal('97.00'), 'Not Classified'),
 ('Mayotte', Decimal('97.00'), 'Not Classified'),
 ('Mayotte', Decimal('96.00'), 'Not Classified'),
 ('Mayotte', Decimal('96.00'), 'Not Classified'),
 ('Mayotte', Decimal('96.00'), 'Not Classified'),
 ('Mozambique', Decimal('55.67'), 'SADC'),
 ('Mozambique', Decimal('58.00'), 'SADC'),
 ('Mozambique', Decimal('60.00'), 'SADC'),
 ('Mozambique', Decimal('62.33'), 'SADC'),
 ('Mozambique', Decimal('64.33'), 'SADC'),
 ('Mozambique', Decimal('66.67'), 'SADC'),
 ('Rwanda', Decimal('63.00'), 'Not Classified'),
 ('Rwanda', Decimal('64.00'), 'Not Classified'),
 ('Rwanda', Decimal('65.00'), 'Not Classified'),
 ('Rwanda', Decimal('65.67'), 'Not Classified'),
 ('Rwanda', Decimal('66.33'), 'Not Classified'),
 ('Rwanda', Decimal('66.33'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Réunion', Decimal('100.00'), 'Not Classified'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('96.00'), 'SADC'),
 ('Seychelles', Decimal('97.00'), 'SADC'),
 ('Somalia', Decimal('50.67'), 'Not Classified'),
 ('Somalia', Decimal('52.00'), 'Not Classified'),
 ('Somalia', Decimal('53.33'), 'Not Classified'),
 ('Somalia', Decimal('54.67'), 'Not Classified'),
 ('Somalia', Decimal('56.33'), 'Not Classified'),
 ('Somalia', Decimal('57.33'), 'Not Classified'),
 ('South Sudan', Decimal('46.33'), 'Not Classified'),
 ('South Sudan', Decimal('46.67'), 'Not Classified'),
 ('South Sudan', Decimal('47.00'), 'Not Classified'),
 ('South Sudan', Decimal('47.67'), 'Not Classified'),
 ('South Sudan', Decimal('48.33'), 'Not Classified'),
 ('South Sudan', Decimal('48.33'), 'Not Classified'),
 ('Uganda', Decimal('55.00'), 'Not Classified'),
 ('Uganda', Decimal('55.67'), 'Not Classified'),
 ('Uganda', Decimal('57.00'), 'Not Classified'),
 ('Uganda', Decimal('58.67'), 'Not Classified'),
 ('Uganda', Decimal('59.33'), 'Not Classified'),
 ('Uganda', Decimal('61.00'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('58.33'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('60.00'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('61.67'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('63.33'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('64.67'), 'Not Classified'),
 ('United Republic of Tanzania', Decimal('65.00'), 'Not Classified'),
 ('Zambia', Decimal('63.67'), 'SADC'),
 ('Zambia', Decimal('64.33'), 'SADC'),
 ('Zambia', Decimal('64.67'), 'SADC'),
 ('Zambia', Decimal('65.33'), 'SADC'),
 ('Zambia', Decimal('66.33'), 'SADC'),
 ('Zambia', Decimal('66.67'), 'SADC'),
 ('Zimbabwe', Decimal('70.00'), 'SADC'),
 ('Zimbabwe', Decimal('69.33'), 'SADC'),
 ('Zimbabwe', Decimal('69.00'), 'SADC'),
 ('Zimbabwe', Decimal('68.67'), 'SADC'),
 ('Zimbabwe', Decimal('68.33'), 'SADC'),
 ('Zimbabwe', Decimal('68.00'), 'SADC'),
 ('Angola', Decimal('50.33'), 'SADC'),
 ('Angola', Decimal('51.00'), 'SADC'),
 ('Angola', Decimal('51.33'), 'SADC'),
 ('Angola', Decimal('52.33'), 'SADC'),
 ('Angola', Decimal('52.33'), 'SADC'),
 ('Angola', Decimal('52.33'), 'SADC'),
 ('Cameroon', Decimal('62.67'), 'Not Classified'),
 ('Cameroon', Decimal('62.67'), 'Not Classified'),
 ('Cameroon', Decimal('63.33'), 'Not Classified'),
 ('Cameroon', Decimal('63.33'), 'Not Classified'),
 ('Cameroon', Decimal('63.33'), 'Not Classified'),
 ('Cameroon', Decimal('64.00'), 'Not Classified'),
 ('Central African Republic', Decimal('44.00'), 'Not Classified'),
 ('Central African Republic', Decimal('42.67'), 'Not Classified'),
 ('Central African Republic', Decimal('41.33'), 'Not Classified'),
 ('Central African Republic', Decimal('40.67'), 'Not Classified'),
 ('Central African Republic', Decimal('39.33'), 'Not Classified'),
 ('Central African Republic', Decimal('38.33'), 'Not Classified'),
 ('Chad', Decimal('51.67'), 'Not Classified'),
 ('Chad', Decimal('52.00'), 'Not Classified'),
 ('Chad', Decimal('52.00'), 'Not Classified'),
 ('Chad', Decimal('52.00'), 'Not Classified'),
 ('Chad', Decimal('52.33'), 'Not Classified'),
 ('Chad', Decimal('52.67'), 'Not Classified'),
 ('Congo', Decimal('66.33'), 'Not Classified'),
 ('Congo', Decimal('67.67'), 'Not Classified'),
 ('Congo', Decimal('68.67'), 'Not Classified'),
 ('Congo', Decimal('68.67'), 'Not Classified'),
 ('Congo', Decimal('69.00'), 'Not Classified'),
 ('Congo', Decimal('69.00'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('45.33'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('45.67'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('46.00'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('46.67'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('47.00'), 'Not Classified'),
 ('Democratic Republic of the Congo', Decimal('47.67'), 'Not Classified'),
 ('Equatorial Guinea', Decimal('57.67'), 'Not Classified'),
 ('Equatorial Guinea', Decimal('57.67'), 'Not Classified'),
 ('Equatorial Guinea', Decimal('58.00'), 'Not Classified'),
 ('Gabon', Decimal('72.00'), 'Not Classified'),
 ('Gabon', Decimal('72.33'), 'Not Classified'),
 ('Gabon', Decimal('73.00'), 'Not Classified'),
 ('Gabon', Decimal('73.00'), 'Not Classified'),
 ('Gabon', Decimal('73.33'), 'Not Classified'),
 ('Gabon', Decimal('73.33'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('76.00'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('76.67'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.00'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.00'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.33'), 'Not Classified'),
 ('Sao Tome and Principe', Decimal('77.33'), 'Not Classified'),
 ('Botswana', Decimal('85.67'), 'SADC'),
 ('Botswana', Decimal('86.67'), 'SADC'),
 ('Botswana', Decimal('87.67'), 'SADC'),
 ('Botswana', Decimal('88.33'), 'SADC'),
 ('Botswana', Decimal('89.67'), 'SADC'),
 ('Botswana', Decimal('89.67'), 'SADC'),
 ('Eswatini', Decimal('73.33'), 'SADC'),
 ('Eswatini', Decimal('74.00'), 'SADC'),
 ('Eswatini', Decimal('75.00'), 'SADC'),
 ('Eswatini', Decimal('75.67'), 'SADC'),
 ('Eswatini', Decimal('76.67'), 'SADC'),
 ('Eswatini', Decimal('76.67'), 'SADC'),
 ('Lesotho', Decimal('74.67'), 'SADC'),
 ('Lesotho', Decimal('75.00'), 'SADC'),
 ('Lesotho', Decimal('75.33'), 'SADC'),
 ('Lesotho', Decimal('76.00'), 'SADC'),
 ('Lesotho', Decimal('76.00'), 'SADC'),
 ('Lesotho', Decimal('76.33'), 'SADC'),
 ('Namibia', Decimal('83.33'), 'SADC'),
 ('Namibia', Decimal('83.00'), 'SADC'),
 ('Namibia', Decimal('83.33'), 'SADC'),
 ('Namibia', Decimal('83.67'), 'SADC'),
 ('Namibia', Decimal('83.67'), 'SADC'),
 ('Namibia', Decimal('83.67'), 'SADC'),
 ('South Africa', Decimal('90.00'), 'SADC'),
 ('South Africa', Decimal('90.33'), 'SADC'),
 ('South Africa', Decimal('91.00'), 'SADC'),
 ('South Africa', Decimal('91.33'), 'SADC'),
 ('South Africa', Decimal('91.67'), 'SADC'),
 ('South Africa', Decimal('92.00'), 'SADC'),
 ('Benin', Decimal('65.33'), 'ECOWAS'),
 ('Benin', Decimal('65.33'), 'ECOWAS'),
 ('Benin', Decimal('65.33'), 'ECOWAS'),
 ('Benin', Decimal('65.67'), 'ECOWAS'),
 ('Benin', Decimal('65.33'), 'ECOWAS'),
 ('Benin', Decimal('65.33'), 'ECOWAS'),
 ('Burkina Faso', Decimal('56.33'), 'ECOWAS'),
 ('Burkina Faso', Decimal('56.00'), 'ECOWAS'),
 ('Burkina Faso', Decimal('55.00'), 'ECOWAS'),
 ('Burkina Faso', Decimal('54.33'), 'ECOWAS'),
 ('Burkina Faso', Decimal('54.00'), 'ECOWAS'),
 ('Burkina Faso', Decimal('53.33'), 'ECOWAS'),
 ('Cabo Verde', Decimal('83.33'), 'ECOWAS'),
 ('Cabo Verde', Decimal('84.33'), 'ECOWAS'),
 ('Cabo Verde', Decimal('85.33'), 'ECOWAS'),
 ('Cabo Verde', Decimal('86.00'), 'ECOWAS'),
 ('Cabo Verde', Decimal('86.67'), 'ECOWAS'),
 ('Cabo Verde', Decimal('87.33'), 'ECOWAS'),
 ("Côte d'Ivoire", Decimal('71.33'), 'ECOWAS'),
 ("Côte d'Ivoire", Decimal('71.00'), 'ECOWAS'),
 ("Côte d'Ivoire", Decimal('71.00'), 'ECOWAS'),
 ("Côte d'Ivoire", Decimal('71.00'), 'ECOWAS'),
 ("Côte d'Ivoire", Decimal('70.67'), 'ECOWAS'),
 ("Côte d'Ivoire", Decimal('70.67'), 'ECOWAS'),
 ('Gambia', Decimal('78.00'), 'ECOWAS'),
 ('Gambia', Decimal('78.33'), 'ECOWAS'),
 ('Gambia', Decimal('78.67'), 'ECOWAS'),
 ('Gambia', Decimal('78.67'), 'ECOWAS'),
 ('Gambia', Decimal('79.33'), 'ECOWAS'),
 ('Gambia', Decimal('79.33'), 'ECOWAS'),
 ('Ghana', Decimal('79.33'), 'ECOWAS'),
 ('Ghana', Decimal('80.33'), 'ECOWAS'),
 ('Ghana', Decimal('81.33'), 'ECOWAS'),
 ('Ghana', Decimal('82.67'), 'ECOWAS'),
 ('Ghana', Decimal('83.67'), 'ECOWAS'),
 ('Ghana', Decimal('84.67'), 'ECOWAS'),
 ('Guinea', Decimal('67.00'), 'ECOWAS'),
 ('Guinea', Decimal('67.00'), 'ECOWAS'),
 ('Guinea', Decimal('67.33'), 'ECOWAS'),
 ('Guinea', Decimal('67.00'), 'ECOWAS'),
 ('Guinea', Decimal('67.00'), 'ECOWAS'),
 ('Guinea', Decimal('67.33'), 'ECOWAS'),
 ('Guinea-Bissau', Decimal('60.00'), 'ECOWAS'),
 ('Guinea-Bissau', Decimal('60.33'), 'ECOWAS'),
 ('Guinea-Bissau', Decimal('60.00'), 'ECOWAS'),
 ('Guinea-Bissau', Decimal('60.00'), 'ECOWAS'),
 ('Guinea-Bissau', Decimal('60.00'), 'ECOWAS'),
 ('Guinea-Bissau', Decimal('60.00'), 'ECOWAS'),
 ('Liberia', Decimal('72.67'), 'ECOWAS'),
 ('Liberia', Decimal('73.00'), 'ECOWAS'),
 ('Liberia', Decimal('74.00'), 'ECOWAS'),
 ('Liberia', Decimal('74.00'), 'ECOWAS'),
 ('Liberia', Decimal('75.00'), 'ECOWAS'),
 ('Liberia', Decimal('75.00'), 'ECOWAS'),
 ('Mali', Decimal('76.00'), 'ECOWAS'),
 ('Mali', Decimal('77.67'), 'ECOWAS'),
 ('Mali', Decimal('79.33'), 'ECOWAS'),
 ('Mali', Decimal('80.67'), 'ECOWAS'),
 ('Mali', Decimal('82.00'), 'ECOWAS'),
 ('Mali', Decimal('83.67'), 'ECOWAS'),
 ('Mauritania', Decimal('66.67'), 'UMA'),
 ('Mauritania', Decimal('68.33'), 'UMA'),
 ('Mauritania', Decimal('70.00'), 'UMA'),
 ('Mauritania', Decimal('70.00'), 'UMA'),
 ('Mauritania', Decimal('70.00'), 'UMA'),
 ('Mauritania', Decimal('70.33'), 'UMA'),
 ('Niger', Decimal('56.67'), 'ECOWAS'),
 ('Niger', Decimal('57.00'), 'ECOWAS'),
 ('Niger', Decimal('57.00'), 'ECOWAS'),
 ('Niger', Decimal('57.00'), 'ECOWAS'),
 ('Niger', Decimal('57.33'), 'ECOWAS'),
 ('Niger', Decimal('57.33'), 'ECOWAS'),
 ('Nigeria', Decimal('69.00'), 'ECOWAS'),
 ('Nigeria', Decimal('71.00'), 'ECOWAS'),
 ('Nigeria', Decimal('72.33'), 'ECOWAS'),
 ('Nigeria', Decimal('74.00'), 'ECOWAS'),
 ('Nigeria', Decimal('75.67'), 'ECOWAS'),
 ('Nigeria', Decimal('77.33'), 'ECOWAS'),

### 4. Calculate the minimum, average, and maximum percentages of managed drinking water services for each REC.

Use the `MIN()`, `AVG()`, and `MAX()` aggregate functions on the `Pct_managed_drinking_water_services` column to obtain the minimum, average, and maximum percentages of managed drinking water services for each REC

Make sure to group the results by the REC using the `GROUP BY` clause to specify how the data should be grouped for the aggregate calculations.

In [12]:
%%sql

SELECT
    CASE
        WHEN 
            Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 'Lesotho', 'Madagascar', 
            'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
        THEN
            'SADC'
        WHEN 
            Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
        THEN
            'UMA'
        WHEN
            Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', "Cote d'Ivoire", 'Gambia', 'Ghana', 
                            'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
        THEN 
            'ECOWAS'
        ELSE 
            'Not Classified'
    END AS Regional_economic_community,
    Country_name,
    Pct_managed_drinking_water_services,
    MIN(Pct_managed_drinking_water_services) as Min_pct_managed_drinking_water_services,
    AVG(Pct_managed_drinking_water_services) as Avg_pct_managed_drinking_water_services,
    MAX(Pct_managed_drinking_water_services) as Max_pct_managed_drinking_water_services
FROM
    united_nations.Access_to_Basic_Services
WHERE region LIKE '%Africa%'
GROUP BY 
        CASE
            WHEN 
                Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 'Lesotho', 'Madagascar', 
                'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
            THEN
                'SADC'
            WHEN 
                Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
            THEN
                'UMA'
            WHEN
                Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', "Cote d'Ivoire", 'Gambia', 'Ghana', 
                                'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
            THEN 
                'ECOWAS'
            ELSE 
                'Not Classified'
        END;

 * mysql+pymysql://root:***@localhost:3306/united_nations
(pymysql.err.OperationalError) (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'united_nations.Access_to_Basic_Services.Country_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT
    CASE
        WHEN
            Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 'Lesotho', 'Madagascar',
            'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
        THEN
            'SADC'
        WHEN
            Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
        THEN
            'UMA'
        WHEN
            Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', "Cote d'Ivoire", 'Gambia', 'Ghana',
                            'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
        THEN
            'ECOWAS'
        ELSE
            'Not Classified'
    END AS Regional_economic_community,
    Country_name,
    Pct_managed_drinking_water_services,
    MIN(Pct_managed_drinking_water_services) as Min_pct_managed_drinking_water_services,
    AVG(Pct_managed_drinking_water_services) as Avg_pct_managed_drinking_water_services,
    MAX(Pct_managed_drinking_water_services) as Max_pct_managed_drinking_water_services
FROM
    united_nations.Access_to_Basic_Services
WHERE region LIKE '%%Africa%%'
GROUP BY
        CASE
            WHEN
                Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 'Lesotho', 'Madagascar',
                'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
            THEN
                'SADC'
            WHEN
                Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
            THEN
                'UMA'
            WHEN
                Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', "Cote d'Ivoire", 'Gambia', 'Ghana',
                                'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
            THEN
                'ECOWAS'
            ELSE
                'Not Classified'
        END;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

## Solutions

### 1. Identify regions in Africa

In [7]:
%%sql

SELECT *
FROM united_nations.Access_to_Basic_Services
WHERE Region LIKE "%Africa%"
LIMIT 5; -- Remove this line to see the full list

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2015, Decimal('92.00'), Decimal('85.00'), Decimal('39.543154'), Decimal('165.98'), Decimal('2381741.00'), Decimal('11.21')),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2016, Decimal('93.00'), Decimal('85.33'), Decimal('40.339329'), Decimal('160.03'), Decimal('2381741.00'), Decimal('10.20')),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2017, Decimal('93.00'), Decimal('84.67'), Decimal('41.136546'), Decimal('170.10'), Decimal('2381741.00'), Decimal('12.00')),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2018, Decimal('93.00'), Decimal('84.67'), Decimal('41.927007'), Decimal('174.91'), Decimal('2381741.00'), None),
 ('Northern Africa and Western Asia', 'Northern Africa', 'Algeria', 2019, Decimal('93.33'), Decimal('84.67'), Decimal('42.705368'), Decimal('171.77'), Decimal('2381741.00'), None)]

### 2. Classify SADC countries

In [8]:
%%sql

SELECT
	CASE 
		WHEN Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 
						 'Lesotho', 'Madagascar', 'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 
						 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
			THEN 'SADC'
		ELSE 'Not Classified'
	END AS Regional_economic_community,
    Country_name,
    Pct_managed_drinking_water_services
FROM united_nations.Access_to_Basic_Services
WHERE Region LIKE "%Africa%"
LIMIT 5; -- Remove this line to see the entire result set

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Not Classified', 'Algeria', Decimal('92.00')),
 ('Not Classified', 'Algeria', Decimal('93.00')),
 ('Not Classified', 'Algeria', Decimal('93.00')),
 ('Not Classified', 'Algeria', Decimal('93.00')),
 ('Not Classified', 'Algeria', Decimal('93.33'))]

### 3. Classify UMA and ECOWAS countries

In [9]:
%%sql

SELECT
	CASE 
		WHEN Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 
						 'Lesotho', 'Madagascar', 'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 
						 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
			THEN 'SADC'
            
		WHEN Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
			THEN 'UMA'
            
        WHEN Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', 'Cote d’Ivoire', 'Gambia', 'Ghana', 'Guinea', 
							'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
			THEN 'ECOWAS'
            
		ELSE 'Not Classified'
	END AS Regional_economic_community,
	Country_name,
	Pct_managed_drinking_water_services
FROM united_nations.Access_to_Basic_Services
WHERE Region LIKE "%Africa%"
LIMIT 5; -- Remove this line to see the entire result set

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('UMA', 'Algeria', Decimal('92.00')),
 ('UMA', 'Algeria', Decimal('93.00')),
 ('UMA', 'Algeria', Decimal('93.00')),
 ('UMA', 'Algeria', Decimal('93.00')),
 ('UMA', 'Algeria', Decimal('93.33'))]

### 4. Calculate the minimum, average, and maximum percentages of managed drinking water services for each REC

We need to use the same `CASE` statement as in our `SELECT` clause to group the countries by their REC. This is because when we group, every non-aggregated column in the `SELECT` clause, such as our `CASE` statement determining the REC, must also be part of the `GROUP BY` clause to ensure data are grouped correctly. Additionally, we need to remove the `Country_name` column from the list of columns that will be returned as it is not an aggregated column, and it is not part of our `GROUP BY` clause.

In [10]:
%%sql

SELECT
	CASE 
		WHEN Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 
						 'Lesotho', 'Madagascar', 'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 
						 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
			THEN 'SADC'
            
		WHEN Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
			THEN 'UMA'
            
        WHEN Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', 'Cote d’Ivoire', 'Gambia', 'Ghana', 'Guinea', 
							'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
			THEN 'ECOWAS'
            
		ELSE 'Not Classified'
	END AS Regional_economic_community,
	MIN(Pct_managed_drinking_water_services) as Min_pct_managed_drinking_water_services,
    AVG(Pct_managed_drinking_water_services) as Avg_pct_managed_drinking_water_services,
    MAX(Pct_managed_drinking_water_services) as Max_pct_managed_drinking_water_services
FROM united_nations.Access_to_Basic_Services
WHERE Region LIKE "%Africa%"
GROUP BY CASE 
			WHEN Country_name IN ('Angola', 'Botswana', 'Comoros', 'Democratic Republic of Congo', 'Eswatini', 
						 'Lesotho', 'Madagascar', 'Malawi', 'Mauritius', 'Mozambique', 'Namibia', 
						 'Seychelles', 'South Africa', 'United Republic Tanzania', 'Zambia', 'Zimbabwe')
			THEN 'SADC'
            
			WHEN Country_name IN ('Algeria', 'Libya', 'Mauritania', 'Morocco', 'Tunisia')
			THEN 'UMA'
            
			WHEN Country_name IN ('Benin', 'Burkina Faso', 'Cabo Verde', 'Cote d’Ivoire', 'Gambia', 'Ghana', 'Guinea', 
							'Guinea-Bissau', 'Liberia', 'Mali', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo')
			THEN 'ECOWAS'
		ELSE 'Not Classified'
	END;

 * mysql+pymysql://root:***@localhost:3306/united_nations
4 rows affected.

[('UMA', Decimal('66.67'), Decimal('88.233000'), Decimal('100.00')),
 ('Not Classified', Decimal('38.33'), Decimal('79.659755'), Decimal('100.00')),
 ('SADC', Decimal('50.33'), Decimal('75.813049'), Decimal('100.00')),
 ('ECOWAS', Decimal('53.33'), Decimal('70.789286'), Decimal('87.33'))]

### Summary

We now have a summarised report by the regional economic community, showcasing the minimum, average, and maximum values of managed drinking water services for each.

#  
<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/EAI_Blue_Dark.png"  style="width:200px";/>
</div>